### ISSUE TITLE
Adapt the `tests.yaml` to contain the reference files

### ISSUE THREAD

**Issue by valentin-seitz** [precice/tutorials#351]
@MakisH proposed a new syntax to describe different test-suites which now extends to add reference data and other arguments needed at runtime to something like: :
```yaml
test-suites:
  openfoam-adapter-pr:
    tutorials:
      - name: flow-over-heated-plate-of-of
        path: ./flow-over-heated-plate:
        case-combination: (fluid-openfoam, solid-openfoam)
        reference-result: ./flow-over-heated-plate/reference-data/fluid-openfoam_solid-openfoam.tar.gz
        runtime_args:
          -   PARALLEL=TRUE
  ```
