### ISSUE TITLE
Add Timeout to kill the simulation when it "hangs"

### ISSUE THREAD

**Issue by valentin-seitz** [precice/tutorials#371]
Proposed syntax:
```
  fenics_test:
    tutorials:
      - path: flow-over-heated-plate
        case_combination:
 
         - fluid-openfoam
         - solid-fenics
        reference_result: ./flow-over-heated-plate/reference-data/fluid-openfoam_solid-fenics.tar.gz
        timeout: 400s
```
