### ISSUE TITLE
System tests: Restrict preCICE time for selected tests

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#402]
Some tests are expected to be taking too long to run. For such cases, it would be nice to have an option to overwrite the `max-time` in the `precice-config.xml`, both for running the test and for the reference results. Something like this in the `tests.yaml`:

```yaml
  openfoam_adapter_pr:
    tutorials:
      - path: flow-over-heated-plate
        case_combination:
          - fluid-openfoam
          - solid-openfoam
        reference_result: ./flow-over-heated-plate/reference-data/fluid-openfoam_solid-openfoam.tar.gz
        max_time: 0.5
```

which would then perform the following change:

```diff
- <max-time value="1" />
+ <max-time value="0.5" />
```

**Comment by valentin-seitz** [comment]
I see the use case, also considering filesize of the generated artifacts. 
My proposal would look be to do the following: 
```yaml
openfoam_adapter_pr:
    tutorials:
      - path: flow-over-heated-plate
        case_combination:
          - fluid-openfoam
          - solid-openfoam
        reference_result: ./flow-over-heated-plate/reference-data/fluid-openfoam_solid-openfoam.tar.gz
        precice_config_override:
          coupling-scheme:
            max-time: value="1"

```
I think this would provide a bit more semantical support in terms of what `max-time` means in that context (namely overriding the precice_config.xml). Another benefit would be the added flexibility (Maybe we want to change the max-iterations too?)
